version: "3"

services:
  postgres:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    build: .
    command: start-dev
    volumes:
      - ./build/libs/:/opt/keycloak/providers/
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres

volumes:
  db:
